[package]
name = "capnp-reader-struct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
capnp = "0.14.6"

[build-dependencies]
capnpc = "0.14.7"
